name: build podman
on: 
  push:
    tags:
      - build*
jobs:
  build-podman:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [ centos7, centos8 ]
    steps:
      - name: Run actions/checkout for this repo
        uses: actions/checkout@v2
        with:
          path: checkout_build_podman
          persist-credentials: false
      - name: read config JSON file
        id: read-config
        run: |
          json="$(cat checkout_build_podman/config/${{ matrix.config }}.json)"
          json="${json//'%'/'%25'}"
          json="${json//$'\r'/'%0D'}"
          json="${json//$'\n'/'%0A'}"
          echo ::set-output "name=config::$json"
      - name: Run actions/setup-go with go version ${{ fromJson(steps.read-config.outputs.config).go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ fromJson(steps.read-config.outputs.config).go_version }}
      - name: mkdir
        run: |
          mkdir $GITHUB_WORKSPACE/output
          mkdir -p $GITHUB_WORKSPACE/gopath/src/github.com/containers
      - name: Run actions/checkout for containers/conmon
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.read-config.outputs.config).gitrepos.conmon.repository }}
          ref: ${{ fromJson(steps.read-config.outputs.config).gitrepos.conmon.ref }}
          path: gopath/src/github.com/containers/conmon
          persist-credentials: false
      - name: Run actions/checkout for containers/podman
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.read-config.outputs.config).gitrepos.podman.repository }}
          ref: ${{ fromJson(steps.read-config.outputs.config).gitrepos.podman.ref }}
          path: gopath/src/github.com/containers/podman
          persist-credentials: false
      # Podman issue 9389 has already been fixed in the Podman master branch
      # (see https://github.com/containers/podman/issues/9389)
      # Remove this workaround later
      - name: Fix Podman issue 9389
        run: |
          bash checkout_build_podman/fix_podman_issue_9389.bash
      - name: Run actions/checkout for CNI/plugins
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.read-config.outputs.config).gitrepos.CNI-plugins.repository }}
          ref: ${{ fromJson(steps.read-config.outputs.config).gitrepos.CNI-plugins.ref }}
          path: gopath/src/github.com/containernetworking/plugins
          persist-credentials: false
      - name: check podman version
        run: |
          podman --version
      - name: podman build
        run: |
          bash checkout_build_podman/build_containerimage.bash ${{ matrix.config }}
      - name: podman run
        run: |
          bash checkout_build_podman/build_podman_wrapper.bash ${{ matrix.config }}
      - name: check output
        run: |
          ls $GITHUB_WORKSPACE/output
      - name: download extra executables
        run: |
          curl -o output/bin/crun -L -s https://github.com/containers/crun/releases/download/${{ matrix.download.crun }}/crun-${{ matrix.download.crun }}-linux-amd64
          chmod 755 output/bin/crun
          curl -o output/bin/slirp4netns -L -s https://github.com/rootless-containers/slirp4netns/releases/download/${{ matrix.download.slirp4netns }}/slirp4netns-x86_64
          chmod 755 output/bin/slirp4netns
          curl -o output/bin/fuse-overlayfs -L -s https://github.com/containers/fuse-overlayfs/releases/download/${{ matrix.download.fuse-overlayfs }}/fuse-overlayfs-x86_64
          chmod 755 output/bin/fuse-overlayfs
      - name: set name
        id: setname
        run: echo ::set-output name=outputname::build-podman_${{ github.sha }}__${{ matrix.config }}__${{ fromJson(steps.read-config.outputs.config).gitrepos.podman.ref }}__${{ fromJson(steps.read-config.outputs.config).gitrepos.conmon.ref }}__${{ fromJson(steps.read-config.outputs.config).gitrepos.CNI-plugins.ref }}__${{ fromJson(steps.read-config.outputs.config).go_version }}__${{ fromJson(steps.read-config.outputs.config).download.crun }}__${{ fromJson(steps.read-config.outputs.config).download.slirp4netns }}__${{ fromJson(steps.read-config.outputs.config).download.fuse-overlayfs }}
      - name: create tar archive
        run: |
          mv output ${{steps.setname.outputs.outputname}}
          tar --force-local -cvf ${{steps.setname.outputs.outputname}}.tar ${{steps.setname.outputs.outputname}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{steps.setname.outputs.outputname}}.tar
          path: ${{steps.setname.outputs.outputname}}.tar
