name: build podman
on: 
  push:
    tags:
      - build*
jobs:
  build-podman:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.15.3]
        podman-version: [c67172ab8880508c86d7b4891a64361730d2a6ea]
        conmon-version: [v2.0.27]
        centos-version: [8, 7]
        CNI-plugins-version: [v0.9.1]
        crun-version: [0.18]
        slirp4netns-version: [v1.1.9]
        fuse-overlayfs-version: [v1.4.0]
        installprefix: [/home/erik.sjolund/podman]
    steps:
      - name: Run actions/setup-go with go-version ${{ matrix.goVersion }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: mkdir
        run: |
          mkdir $GITHUB_WORKSPACE/output
          mkdir -p $GITHUB_WORKSPACE/gopath/src/github.com/containers
      - name: Run actions/checkout for this repo
        uses: actions/checkout@v2
        with:
          path: checkout_build_podman
          persist-credentials: false
      - name: Run actions/checkout for containers/conmon
        uses: actions/checkout@v2
        with:
          repository: containers/conmon
          ref: ${{ matrix.conmon-version }}
          path: gopath/src/github.com/containers/conmon
          persist-credentials: false
      - name: Run actions/checkout for containers/podman
        uses: actions/checkout@v2
        with:
          repository: containers/podman
          ref: ${{ matrix.podman-version }}
          path: gopath/src/github.com/containers/podman
          persist-credentials: false
      - name: Run actions/checkout for CNI/plugins
        uses: actions/checkout@v2
        with:
          repository: containernetworking/plugins
          ref: ${{ matrix.CNI-plugins-version }}
          path: gopath/src/github.com/containernetworking/plugins
          persist-credentials: false
      - name: podman run
        run: |
          podman run --rm -v $GITHUB_WORKSPACE/output:${{ matrix.installprefix }} -v $GITHUB_WORKSPACE/checkout_build_podman:/checkout_build_podman -v /opt/hostedtoolcache/go:/opt/hostedtoolcache/go -v $GITHUB_WORKSPACE/gopath:/gopath -e GOROOT=/opt/hostedtoolcache/go/${{ matrix.go-version }}/x64 -e PATH=/opt/hostedtoolcache/go/${{ matrix.go-version }}/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin docker.io/clinicalgenomics/build-podman:centos${{ matrix.centos-version }} bash /checkout_build_podman/container_build_command.sh ${{ matrix.installprefix }}
      - name: check output
        run: |
          ls $GITHUB_WORKSPACE/output
      - name: download extra executables
        run: |
          curl -o output/bin/crun -L -s https://github.com/containers/crun/releases/download/${{ matrix.crun-version }}/crun-${{ matrix.crun-version }}-linux-amd64
          chmod 755 output/bin/crun
          curl -o output/bin/slirp4netns -L -s https://github.com/rootless-containers/slirp4netns/releases/download/${{ matrix.slirp4netns-version }}/slirp4netns-x86_64
          chmod 755 output/bin/slirp4netns
          curl -o output/bin/fuse-overlayfs -L -s https://github.com/containers/fuse-overlayfs/releases/download/${{ matrix.fuse-overlayfs-version }}/fuse-overlayfs-x86_64
          chmod 755 output/bin/fuse-overlayfs
      - name: create tar archive
        run: |
          tar -cvf build-podman_${{ github.sha }}__${{ matrix.centos-version }}__${{ matrix.podman-version }}__${{ matrix.conmon-version }}__${{ matrix.CNI-plugins-version }}__${{ matrix.go-version }}__${{ matrix.crun-version }}__${{ matrix.slirp4netns-version }}__${{ matrix.fuse-overlayfs-version }}.tar output
      - uses: actions/upload-artifact@v2
        with:
          name: bui_${{ github.sha }}__co_${{ matrix.centos-version }}__podman_${{ matrix.podman-version }}__conmon_${{ matrix.conmon-version }}__CNI-plugins_${{ matrix.CNI-plugins-version }}__go_${{ matrix.go-version }}__crun_${{ matrix.crun-version }}__slirp4netns_${{ matrix.slirp4netns-version }}__fuse-overlayfs_${{ matrix.fuse-overlayfs-version }}.tar
          path: build-podman_${{ github.sha }}__${{ matrix.centos-version }}__${{ matrix.podman-version }}__${{ matrix.conmon-version }}__${{ matrix.CNI-plugins-version }}__${{ matrix.go-version }}__${{ matrix.crun-version }}__${{ matrix.slirp4netns-version }}__${{ matrix.fuse-overlayfs-version }}.tar