name: Build and push container images
on:
  push:
    tags:
      - publish-container-dockerhub*
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos-version: [8.2.2004, 7.7.1908]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eriksjolund/build-podman:centos${{ matrix.centos-version }}
          build-args: |
            CENTOS_VERSION=${{ matrix.centos-version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
